### ISSUE TITLE
perf: unswitch loop, fast path for min == zero

### ISSUE THREAD

**Issue by milahu** [dy/array-normalize#2]
this could be faster ..
```js
else {
  var range = max - min
  for (i = offset; i < l; i+=dim) {
    if (!isNaN(arr[i])) {
      arr[i] = range === 0 ? .5 : (arr[i] - min) / range
    }
  }
}
```
like
```js
else if (min == max) {
  for (i = offset; i < l; i+=dim) {
    if (!isNaN(arr[i])) {
      arr[i] = .5
    }
  }
}
else if (min == 0) {
  for (i = offset; i < l; i+=dim) {
    arr[i] = arr[i] / range
  }
}
else {
  for (i = offset; i < l; i+=dim) {
    arr[i] = (arr[i] - min) / range
  }
}
```
the NaN test is not needed, since `NaN / range` and `(NaN - min) / range` always equal `NaN`
JS does not unswitch loops like a C compiler would

**Comment by dy** [comment]
makes sense I guess. Would be nice to benchmark. PR welcome!

**Comment by milahu** [comment]
> Would be nice to benchmark

https://jsbench.github.io/#ad362c5589fab6e17498939f5343310d

gains are almost zero, at least on modern JS interpreters

**Comment by dy** [comment]
Ok, expanded loop in v2.0
